# Generated by Django 4.0.1 on 2022-01-26 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='emails',
            new_name='email',
        ),
    ]
